# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xiaomi/wayne-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)
ifneq ($(filter jasmine_sprout wayne,$(TARGET_DEVICE)),)

include $(CLEAR_VARS)
LOCAL_MODULE       := MIUI_DualCamera_watermark
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := ETC
ifeq ($(TARGET_DEVICE),jasmine_sprout)
LOCAL_SRC_FILES    := etc/MIUI_DualCamera_watermark_A2.png
else ifeq ($(TARGET_DEVICE),wayne)
LOCAL_SRC_FILES    := etc/MIUI_DualCamera_watermark_6X.png
endif
LOCAL_MODULE_PATH  := $(TARGET_OUT_VENDOR_ETC)
include $(BUILD_PREBUILT)

endif
